name: "Publish to Maven"

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build-and-publish:
    permissions:
      contents: read
      packages: write
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Set Up JDK"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew

      - name: "Build with Gradle"
        run: ./gradlew build -x :ktor-simple-redis-cache:jvmTest
        shell: bash

      - name: "Decode GPG Key"
        run: |
          echo "${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}" > ~/.gradle/secring.gpg.b64
          base64 --decode -i ~/.gradle/secring.gpg.b64 -o ~/.gradle/secring.gpg
        shell: bash

      - name: "Publish"
        env:
          PAT: ${{ secrets.PAT }}
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository -Psigning.keyId=${{ secrets.SIGNING_KEY_ID }} -Psigning.password=${{ secrets.SIGNING_PASSWORD }} -Psigning.secretKeyRingFile=$(echo ~/.gradle/secring.gpg)